In [2]:
import numpy as np
import matplotlib.pyplot as plt
import torch


## General tensor commands

In [8]:
# Creating a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

# Mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

# sum
x.sum(), torch.sum(x)

# argmin and argmax - returns indeces of min and max
x.argmin(), x.argmax()


(tensor(0), tensor(9))

### Reshaping, stacking, squeezing and unsqueezing tensors 
- Reshaping reshapes tensor into defined shape
- View, view a part of a tensor, without changing it
- Stacking concatenates tensors vertically or horyzontally
- Squeeze removes all '1' dimensions from a tensor


In [32]:
x = torch.arange(1.,10)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [33]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [40]:
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [46]:
x[0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [59]:
# stacking tensors
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [62]:
# Squeezing tensors
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [65]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [79]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [92]:
# torch.permute
x_img = torch.rand(size=(224, 224, 3))
x_img_permuted = x_img.permute(2, 0, 1)
print(f"Previous shape: {x_img.shape}")
print(f"New shape {x_img_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape torch.Size([3, 224, 224])


## PyTorch with numpy
Be aware of datatypes

## Pytorch fundamentals exercises
Skipped some, continued video

In [185]:
e1 = torch.rand(7,7)
print(f"Exercise 1: {e1, e1.dtype}")

e2 = torch.rand(1,7).transpose(0,1).type(torch.float64)

e2_sol = e2*e1

print(f"Exercise 2: {e2_sol.shape, e2_sol.dtype}")

seed = 0

Exercise 1: (tensor([[0.1957, 0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730],
        [0.6186, 0.6962, 0.5300, 0.2560, 0.7366, 0.0204, 0.2036],
        [0.3748, 0.2564, 0.3251, 0.0902, 0.3936, 0.6069, 0.1743],
        [0.4743, 0.8579, 0.4486, 0.5139, 0.4569, 0.6012, 0.8179],
        [0.9736, 0.8175, 0.9747, 0.4638, 0.0508, 0.2630, 0.8405],
        [0.4968, 0.2515, 0.1168, 0.0321, 0.0780, 0.3986, 0.7742],
        [0.7703, 0.0178, 0.8119, 0.1087, 0.3943, 0.2973, 0.4037]]), torch.float32)
Exercise 2: (torch.Size([7, 7]), torch.float64)


## PyTorch workflow

In [193]:
what_were_covering = {1: "Data",
                      2: "Model building",
                      3: "Fitting the model to data (training)",
                      4: "Make predictions",
                      5: "Experiment",
                      6: "Save model"}
